Feature/#0034 code refactoring
0-Auth/0Auth pull request #75
Opened 2020-10-05 14:13 UTC by anthonyminyungi

# Summary 

- It closes #34 

## How to Review? 

- Please refer to my self-review submitted as the review.

## Images 

## Further Work

2020-10-05 14:17 UTC, anthonyminyungi reviewed
Self-review.

I re-arranged the functions by the feature of each function.
I think you would better to check these changes by your editor to check the directories than by directly in this viewer.

2020-10-06 10:32 UTC, HyeockJinKim requested changes
Please check the review details.

2020-10-06 10:32 UTC, HyeockJinKim commented on packages/server/src/authenticator/index.ts
> +export { authPackage, authPrivacy, authProperty, authByAuthType };
I think it would be better to export immediately rather than export after import.
like this: 
`export * from './authPackage';`

2020-10-06 10:32 UTC, HyeockJinKim commented on packages/server/src/index.ts
> +  publicKeyFromSecret,
Same as above comment.

2020-10-06 10:32 UTC, HyeockJinKim commented on packages/server/src/authenticator/authByAuthType.ts
> +}
The name ʻauthenticator` seems inappropriate.
Wouldn't it be better to just have an ʻissuer` folder instead of an ʻauthenticator`?

2020-10-06 10:32 UTC, HyeockJinKim commented on packages/server/src/util/getMerkleRoot.ts
> +}
By default, the folder name ʻutils` is mainly used.
I think it would be better to use the ʻutils` folder name than ʻutil`.

2020-10-06 10:41 UTC, HyeockJinKim commented
And if you do `closes #34`, issue 34 is closed even if the rest of the PR is not completed.
You must use `Related to #34`.

2020-10-06 11:11 UTC, anthonyminyungi reviewed
Review reflected.

2020-10-06 11:11 UTC, anthonyminyungi commented on packages/server/src/issuer/authByAuthType.ts
> +  type: AuthType,
Directory moved. `authenticator` -> `issuer`.

2020-10-06 11:11 UTC, anthonyminyungi commented on package.json
> +    "lint": "eslint packages/**/src/**/*.ts"
The 1-level of depth is added.

2020-10-06 11:11 UTC, anthonyminyungi commented on packages/server/src/utils/signByKeyType.ts
> +  secret: string,
The directory name was changed `util` -> `utils`.

2020-10-06 11:47 UTC, HyeockJinKim approved these changes
It looks good to me.

2020-10-06 11:47 UTC, merged